create table UserAccount( 
  First_Name VARCHAR(255) NOT NULL,
  Last_Name VARCHAR(255) NOT NULL,
  FULL_Name VARCHAR(255) NOT NULL,
  NIC CHAR(12) NOT NULL,
  PassportNO CHAR(12),
  Gender CHAR(7) NOT NULL,
  Telephone INT(10) NOT NULL,
  Email VARCHAR(255),
  MaritalStatus CHAR(15) NOT NULL,
  Home VARCHAR(255) NOT NULL,
  City VARCHAR(255) NOT NULL,
  Province VARCHAR(255) NOT NULL,
  AccountType VARCHAR(255) NOT NULL,
  Username VARCHAR(255) NOT NULL,
  Apassword VARCHAR(255) NOT NULL,
  AccountNo INT PRIMARY KEY AUTO_INCREMENT,
  AccountBalance FLOAT(12),
  CardType CHAR(20)
);

ALTER TABLE UserAccount AUTO_INCREMENT = 10001;